### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by VanLaser** [hccoffin/ble_footpedal#1]
Just a quick thank you, your touchpad code is a hidden gem! I have an Azoteq TPS65 and an Arduino Feather Sense, and for the life of me couldn't find a good BLE HID over GATT touchpad example. At first I thought it only handles two fingers, but after a good reading of the MS HID touchpad docs, I understood that using hybrid mode your example can go to 4, and I can easily extend it to 5 fingers :) (which I did) Again, cool stuff, thanks!

**Comment by hccoffin** [comment]
Happy to have helped!
Just a note in case you run into issues when you connect the touchpad: I haven't looked at this code for a while, but I remember getting Windows to recognize the touchpad was fairly finicky, and I don't think it ever worked with Apple products. Never had problems in Linux.

**Comment by VanLaser** [comment]
I understand - so far I'm lucky in that I intend to use the touchpad with a Surface Go 3 tablet that has Linux installed :)
